// Code generated by sqlc. DO NOT EDIT.
// source: create_user.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username,
                   email,
                   password_hash,
                   created_at,
                   updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id
`

type CreateUserParams struct {
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}
