// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
)

type Address struct {
	ID           int32          `json:"id"`
	UserID       sql.NullInt32  `json:"user_id"`
	AddressLine1 sql.NullString `json:"address_line1"`
	AddressLine2 sql.NullString `json:"address_line2"`
	City         sql.NullString `json:"city"`
	State        sql.NullString `json:"state"`
	Country      sql.NullString `json:"country"`
	ZipCode      sql.NullString `json:"zip_code"`
	AddressType  sql.NullString `json:"address_type"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Order struct {
	ID          int32          `json:"id"`
	UserID      sql.NullInt32  `json:"user_id"`
	AddressID   sql.NullInt32  `json:"address_id"`
	PaymentID   sql.NullInt32  `json:"payment_id"`
	OrderStatus sql.NullString `json:"order_status"`
	TotalPrice  sql.NullString `json:"total_price"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type OrderItem struct {
	ID             int32          `json:"id"`
	OrderID        sql.NullInt32  `json:"order_id"`
	SkuID          sql.NullInt32  `json:"sku_id"`
	PurchaseTypeID sql.NullInt32  `json:"purchase_type_id"`
	Quantity       sql.NullInt32  `json:"quantity"`
	PricePerItem   sql.NullString `json:"price_per_item"`
	TotalPrice     sql.NullString `json:"total_price"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type Payment struct {
	ID            int32          `json:"id"`
	UserID        sql.NullInt32  `json:"user_id"`
	PaymentType   sql.NullString `json:"payment_type"`
	Provider      sql.NullString `json:"provider"`
	AccountNumber sql.NullString `json:"account_number"`
	ExpiryDate    sql.NullTime   `json:"expiry_date"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Product struct {
	ID          int32        `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CategoryID  int32        `json:"category_id"`
	ImageUrl    string       `json:"image_url"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type ProductSkusPurchaseType struct {
	ID             int32          `json:"id"`
	SkuID          sql.NullInt32  `json:"sku_id"`
	PurchaseTypeID sql.NullInt32  `json:"purchase_type_id"`
	OverridePrice  sql.NullString `json:"override_price"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type PurchaseType struct {
	ID       int32          `json:"id"`
	TypeName sql.NullString `json:"type_name"`
}

type Sku struct {
	ID            int32          `json:"id"`
	ProductID     int32          `json:"product_id"`
	SkuName       string         `json:"sku_name"`
	SinglePrice   sql.NullString `json:"single_price"`
	SubsPrice     sql.NullString `json:"subs_price"`
	StockQuantity int32          `json:"stock_quantity"`
}

type User struct {
	ID           int32  `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Address      string `json:"address"`
	Phone        string `json:"phone"`
}
