// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package database

import (
	"context"
)

const checkUserPassword = `-- name: CheckUserPassword :one
SELECT password_hash
FROM users
WHERE email = $1
`

func (q *Queries) CheckUserPassword(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, checkUserPassword, email)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const createUser = `-- name: CreateUser :many
INSERT INTO users (username,
                   email,
                   password_hash,
                   address,
                   phone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, address, phone
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Address      string `json:"address"`
	Phone        string `json:"phone"`
}

type CreateUserRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	Phone    string `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) ([]CreateUserRow, error) {
	rows, err := q.db.QueryContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Address,
		arg.Phone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateUserRow
	for rows.Next() {
		var i CreateUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Address,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT username,
       email,
       address,
       phone
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	Phone    string `json:"phone"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.Address,
		&i.Phone,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id,
       username,
       email,
       password_hash
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           int32  `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id,
       username,
       email
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
